### ISSUE TITLE
Connectivity issue

### ISSUE THREAD

**Issue by uzairmukadam** [SaharshPandey/Messenger#1]
I followed all the steps and added my Firebase details. I was able to create an account and even login to that account, but later on entering to the main page the app just gets stuck on loading. Can I get your final apk as well as the solution to my problem. Thank you

**Comment by SaharshPandey** [comment]
You can try it again, as there were some wrong data added to Database which causing errors, now that I have fixed it, you can try the app again. Thank you.

**Comment by SaharshPandey** [comment]
I think this issue is resolved. So I'm closing it.

**Comment by usman-assign** [comment]
I have also that problem
